### ISSUE TITLE
a small surprise

### ISSUE THREAD

**Issue by noffle** [cabal-club/commons#9]
Hi y'all! If you've been mentioned on this issue, then you probably made contributions to cabal. Thanks, that was awesome of you! :heart:

A couple of us are assembling *a small surprise*, which we require mailing addresses for. If you're interested in this *small surprise*, please **send a suitable _physical_ mailing address** to `noffle` at `eight45.net`.

If you know of others who weren't included in this list, feel free to ask them to email me too.

@cblgh @nikolaiwarner @kodedninja @okdistribute @ralphtheninja @voidcase @masukomi @telamon @longears @Powersource @MarkBennett @VirtualWolf @slmyers @KidkArolis @luandro @d4tocchini @fenwick67 @lachenmayer @saranrapjs @callil @ahdinosaur @simbolo @joehand @stephenmathieson @staltz @varenc @pvh @SirRujak @brortao

**Comment by noffle** [comment]
I forgot some folx!

cc @substack @Frando @pfrazee @micahscopes @rangermauve

**Comment by okdistribute** [comment]
woo exciting!

**Comment by noffle** [comment]
Please let us know by March 21 or we'll assume you aren't interested. :heart:

**Comment by noffle** [comment]
Thanks everyone who replied <3

**Comment by todrobbins** [comment]
😢 ❤️
